[project]
name = "gld-platform"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "streamlit",
    "streamlit-aggrid",
    "pandas>=2.0",
    "rsconnect-python",
    "databricks-sql-connector[pyarrow]",
    "databricks-sdk",
    "tornado",
    "pyyaml>=6.0.3",
    "python-dotenv>=1.2.2",
]

[tool.uv]
dev-dependencies = []
